import type { Job, SkillRequirement } from './types'

/** Terse helper so the corpus below stays readable: `s('react:3','css:2')`. */
function s(...specs: string[]): SkillRequirement[] {
  return specs.map((spec) => {
    const [id, importance] = spec.split(':')
    return { id, importance: Number(importance) as 1 | 2 | 3 }
  })
}

export const REGIONS = ['North America', 'Europe', 'Asia Pacific', 'Latin America'] as const

export const JOBS: Job[] = [
  {
    id: 'j1',
    title: 'Senior Frontend Engineer',
    company: 'Lumen Labs',
    companyLogo: 'LL',
    blurb: 'Own the design system powering a product used by 4M developers.',
    description:
      'We are looking for a senior frontend engineer to lead the evolution of our component library and design system. You will work shoulder to shoulder with design to ship an accessible, fast, beautifully animated interface, and set the technical direction for how the rest of the product engineering org builds UI.',
    responsibilities: [
      'Architect and maintain our React + TypeScript component library',
      'Drive Core Web Vitals improvements across the marketing and app surfaces',
      'Partner with design on motion, interaction and accessibility standards',
      'Mentor three mid-level engineers through code review and pairing',
    ],
    perks: ['Fully remote', '4-day week trial', '$3k learning budget', 'Equity'],
    skills: s('react:3', 'typescript:3', 'css:3', 'designsystems:2', 'a11y:2', 'testing:2', 'webperf:2', 'animation:1'),
    seniority: 'senior',
    minYears: 5,
    workMode: 'remote',
    location: 'Remote — Global',
    region: 'North America',
    employmentType: 'full-time',
    salaryMin: 145000,
    salaryMax: 185000,
    currency: 'USD',
    tags: ['devtools', 'design systems', 'saas'],
    teamSize: 34,
    postedDaysAgo: 2,
    applicants: 84,
    featured: true,
  },
  {
    id: 'j2',
    title: 'Web Developer',
    company: 'Northwind Studio',
    companyLogo: 'NS',
    blurb: 'Build marketing sites and web apps for culture-defining brands.',
    description:
      'Northwind is a fifteen-person studio that builds award-winning websites for clients in fashion, music and publishing. We want a web developer who cares about craft — pixel-accurate layouts, buttery animation, and HTML that still works with JavaScript switched off.',
    responsibilities: [
      'Translate Figma designs into responsive, semantic HTML and CSS',
      'Build interactive components in React and vanilla JavaScript',
      'Optimise pages for Lighthouse scores above 95',
      'Work directly with clients during review sessions',
    ],
    perks: ['Hybrid 2 days', 'Conference budget', 'Latest hardware', 'Profit share'],
    skills: s('html:3', 'css:3', 'javascript:3', 'react:2', 'responsive:2', 'animation:2', 'figma:1', 'seo:1'),
    seniority: 'mid',
    minYears: 2,
    workMode: 'hybrid',
    location: 'Austin, TX',
    region: 'North America',
    employmentType: 'full-time',
    salaryMin: 85000,
    salaryMax: 115000,
    currency: 'USD',
    tags: ['agency', 'creative', 'ecommerce'],
    teamSize: 15,
    postedDaysAgo: 1,
    applicants: 41,
    featured: true,
  },
  {
    id: 'j3',
    title: 'Full-Stack Engineer',
    company: 'Cobalt Health',
    companyLogo: 'CH',
    blurb: 'Ship patient-facing software that people actually depend on.',
    description:
      'Cobalt builds the scheduling and records layer used by 900 clinics. This is a full-stack role: you will own features end to end, from the Postgres schema through the REST API to the React interface that a nurse uses at 3am. Reliability and clarity matter more here than novelty.',
    responsibilities: [
      'Design and ship features across a Node.js and React stack',
      'Model data in PostgreSQL with an eye on migration safety',
      'Write integration tests that gate every deploy',
      'Participate in a light on-call rotation',
    ],
    perks: ['Remote-first', 'Health + dental', '401k match', 'Sabbatical at 4 years'],
    skills: s('react:3', 'nodejs:3', 'typescript:2', 'postgres:2', 'restapi:2', 'testing:2', 'auth:2', 'aws:1'),
    seniority: 'mid',
    minYears: 3,
    workMode: 'remote',
    location: 'Remote — US',
    region: 'North America',
    employmentType: 'full-time',
    salaryMin: 120000,
    salaryMax: 155000,
    currency: 'USD',
    tags: ['healthtech', 'saas'],
    teamSize: 60,
    postedDaysAgo: 4,
    applicants: 132,
  },
  {
    id: 'j4',
    title: 'Junior Frontend Developer',
    company: 'Peartree',
    companyLogo: 'PT',
    blurb: 'Your first real engineering job, with real mentorship attached.',
    description:
      'We hire junior developers deliberately and support them properly. You will be paired with a senior engineer for your first six months, working on our customer dashboard. We care that you can read code, ask good questions, and write CSS you are not ashamed of.',
    responsibilities: [
      'Build UI components from designs with guidance',
      'Fix bugs reported by the support team',
      'Write your first unit tests and get them reviewed',
      'Present a demo at the fortnightly team showcase',
    ],
    perks: ['Structured mentorship', 'Hybrid', 'Study time on Fridays', 'Gym stipend'],
    skills: s('html:3', 'css:3', 'javascript:3', 'react:2', 'git:2', 'responsive:1', 'testing:1'),
    seniority: 'junior',
    minYears: 0,
    workMode: 'hybrid',
    location: 'Manchester, UK',
    region: 'Europe',
    employmentType: 'full-time',
    salaryMin: 32000,
    salaryMax: 42000,
    currency: 'USD',
    tags: ['saas', 'b2b'],
    teamSize: 22,
    postedDaysAgo: 6,
    applicants: 310,
  },
  {
    id: 'j5',
    title: 'AI Product Engineer',
    company: 'Vector Foundry',
    companyLogo: 'VF',
    blurb: 'Turn frontier models into products people can actually use.',
    description:
      'You will sit between the model and the user, building the retrieval pipelines, evaluation harnesses and interfaces that make an LLM feel reliable. Half the job is prompt and context engineering; the other half is a genuinely excellent streaming React interface.',
    responsibilities: [
      'Build RAG pipelines and evaluate them with real datasets',
      'Design streaming, interruptible chat interfaces in React',
      'Instrument quality metrics and run offline evals',
      'Work with researchers to productionise new capabilities',
    ],
    perks: ['Equity', 'Remote', 'Compute budget', 'Research Fridays'],
    skills: s('llm:3', 'python:3', 'react:2', 'typescript:2', 'restapi:2', 'ml:2', 'websockets:1', 'observability:1'),
    seniority: 'senior',
    minYears: 4,
    workMode: 'remote',
    location: 'Remote — Global',
    region: 'North America',
    employmentType: 'full-time',
    salaryMin: 170000,
    salaryMax: 230000,
    currency: 'USD',
    tags: ['ai', 'devtools', 'saas'],
    teamSize: 28,
    postedDaysAgo: 1,
    applicants: 219,
    featured: true,
  },
  {
    id: 'j6',
    title: 'Frontend Engineer, Growth',
    company: 'Payload',
    companyLogo: 'PL',
    blurb: 'Own the funnel. Ship experiments weekly. Watch the graph move.',
    description:
      'Growth engineering at Payload means owning the surfaces where users first meet the product: landing pages, onboarding, pricing, checkout. You will run A/B tests, obsess over load time, and delete more code than you write.',
    responsibilities: [
      'Ship and analyse A/B tests across acquisition surfaces',
      'Build fast, SEO-friendly pages with Next.js',
      'Instrument funnels and interpret the results honestly',
      'Reduce time-to-interactive on the signup flow',
    ],
    perks: ['Remote in EU', 'Quarterly offsites', 'Equity', 'Home office budget'],
    skills: s('nextjs:3', 'react:3', 'typescript:2', 'analytics:2', 'seo:2', 'webperf:2', 'css:2', 'tailwind:1'),
    seniority: 'mid',
    minYears: 3,
    workMode: 'remote',
    location: 'Remote — Europe',
    region: 'Europe',
    employmentType: 'full-time',
    salaryMin: 78000,
    salaryMax: 105000,
    currency: 'USD',
    tags: ['fintech', 'saas', 'growth'],
    teamSize: 90,
    postedDaysAgo: 3,
    applicants: 96,
  },
  {
    id: 'j7',
    title: 'Staff Software Engineer, Platform',
    company: 'Meridian',
    companyLogo: 'MD',
    blurb: 'Set the technical direction for infrastructure serving 40M requests/day.',
    description:
      'A staff-level role with real scope. You will lead the platform group through a migration from a monolith to well-bounded services, define the standards other teams build against, and be the person the org trusts when something is genuinely hard.',
    responsibilities: [
      'Lead architecture for the service decomposition programme',
      'Define the deployment, observability and reliability standards',
      'Mentor senior engineers and grow the technical bench',
      'Own capacity planning and cost efficiency',
    ],
    perks: ['Equity refresh', 'Hybrid', 'Sabbatical', 'Full family health'],
    skills: s('architecture:3', 'go:3', 'kubernetes:3', 'microservices:3', 'aws:2', 'observability:2', 'postgres:2', 'terraform:1'),
    seniority: 'staff',
    minYears: 8,
    workMode: 'hybrid',
    location: 'Seattle, WA',
    region: 'North America',
    employmentType: 'full-time',
    salaryMin: 220000,
    salaryMax: 290000,
    currency: 'USD',
    tags: ['infrastructure', 'saas', 'b2b'],
    teamSize: 400,
    postedDaysAgo: 8,
    applicants: 57,
  },
  {
    id: 'j8',
    title: 'UI Engineer',
    company: 'Aperture',
    companyLogo: 'AP',
    blurb: 'Sit between design and engineering, and make both better.',
    description:
      'Aperture makes video editing software for the web. We want someone who thinks in both Figma and CSS — an engineer who can take a rough motion study and turn it into a 60fps interaction, and who will push back when a design will not survive contact with real data.',
    responsibilities: [
      'Prototype and ship complex interactive UI in React',
      'Build and document the shared component library in Storybook',
      'Own animation and micro-interaction quality across the app',
      'Audit and fix accessibility issues',
    ],
    perks: ['On-site lunches', 'Equity', 'Creative sabbatical', 'Transit pass'],
    skills: s('react:3', 'css:3', 'animation:3', 'designsystems:2', 'figma:2', 'typescript:2', 'a11y:2', 'uiux:1'),
    seniority: 'mid',
    minYears: 3,
    workMode: 'onsite',
    location: 'Berlin, Germany',
    region: 'Europe',
    employmentType: 'full-time',
    salaryMin: 72000,
    salaryMax: 95000,
    currency: 'USD',
    tags: ['creative', 'media', 'saas'],
    teamSize: 45,
    postedDaysAgo: 5,
    applicants: 73,
  },
  {
    id: 'j9',
    title: 'Backend Engineer, Payments',
    company: 'Ledgerline',
    companyLogo: 'LG',
    blurb: 'Move money correctly. Every single time.',
    description:
      'Payments engineering is unforgiving and that is the appeal. You will work on ledgers, reconciliation and idempotency — systems where a rounding error is an incident. Strong opinions about database transactions welcome.',
    responsibilities: [
      'Design and build ledger and reconciliation services',
      'Guarantee idempotency and exactly-once semantics across retries',
      'Integrate new payment providers and settlement rails',
      'Write the runbooks for the systems you own',
    ],
    perks: ['Remote', 'Equity', 'Learning budget', 'Health cover'],
    skills: s('go:3', 'postgres:3', 'restapi:3', 'microservices:2', 'testing:2', 'auth:2', 'redis:1', 'observability:1'),
    seniority: 'senior',
    minYears: 5,
    workMode: 'remote',
    location: 'Remote — US',
    region: 'North America',
    employmentType: 'full-time',
    salaryMin: 155000,
    salaryMax: 200000,
    currency: 'USD',
    tags: ['fintech', 'b2b'],
    teamSize: 120,
    postedDaysAgo: 7,
    applicants: 68,
  },
  {
    id: 'j10',
    title: 'Frontend Developer (Contract)',
    company: 'Halcyon Retail',
    companyLogo: 'HR',
    blurb: 'Six-month contract rebuilding a storefront that does $200M a year.',
    description:
      'We are replatforming our storefront and need an experienced frontend contractor for six months. The work is well-defined: rebuild the product listing, detail and checkout pages in Next.js against an existing commerce API. Extension likely.',
    responsibilities: [
      'Rebuild core storefront pages in Next.js',
      'Integrate against an existing commerce REST API',
      'Hit strict Core Web Vitals targets on mobile',
      'Hand over clean, documented code at the end of the engagement',
    ],
    perks: ['Fully remote', 'Day rate', 'Possible extension', 'Async-first'],
    skills: s('nextjs:3', 'react:3', 'typescript:2', 'css:2', 'restapi:2', 'webperf:2', 'responsive:2'),
    seniority: 'senior',
    minYears: 5,
    workMode: 'remote',
    location: 'Remote — Global',
    region: 'Europe',
    employmentType: 'contract',
    salaryMin: 110000,
    salaryMax: 140000,
    currency: 'USD',
    tags: ['ecommerce', 'retail'],
    teamSize: 210,
    postedDaysAgo: 9,
    applicants: 44,
  },
  {
    id: 'j11',
    title: 'Software Engineer, Developer Experience',
    company: 'Forge',
    companyLogo: 'FG',
    blurb: 'Your users are engineers. Your product is their whole day.',
    description:
      'DevEx at Forge owns the build system, the CI pipeline, the local development environment and the internal CLI. If you have ever been annoyed by a slow test suite and then actually fixed it, this is your job.',
    responsibilities: [
      'Cut CI times and keep the build graph healthy',
      'Build internal CLIs and generators engineers actually like',
      'Maintain the local dev environment across three platforms',
      'Measure and improve developer satisfaction quantitatively',
    ],
    perks: ['Remote', '20% time', 'Equity', 'Top-tier hardware'],
    skills: s('typescript:3', 'nodejs:3', 'cicd:3', 'docker:2', 'webpack:2', 'testing:2', 'git:2', 'observability:1'),
    seniority: 'senior',
    minYears: 4,
    workMode: 'remote',
    location: 'Remote — Global',
    region: 'North America',
    employmentType: 'full-time',
    salaryMin: 150000,
    salaryMax: 190000,
    currency: 'USD',
    tags: ['devtools', 'infrastructure'],
    teamSize: 75,
    postedDaysAgo: 3,
    applicants: 91,
  },
  {
    id: 'j12',
    title: 'Web Developer, Nonprofit Sector',
    company: 'Open Commons',
    companyLogo: 'OC',
    blurb: 'Accessible, resilient websites for organisations doing real good.',
    description:
      'We build for charities, libraries and civic organisations. Budgets are small, so the work rewards pragmatism: server-rendered pages, progressive enhancement, and accessibility taken seriously rather than performed. Our sites work on a ten-year-old phone over 3G.',
    responsibilities: [
      'Build accessible, standards-compliant websites',
      'Meet WCAG 2.2 AA on every project without exception',
      'Work with non-technical stakeholders to scope realistically',
      'Maintain and improve a shared template library',
    ],
    perks: ['Remote', '35-hour week', 'Extra leave', 'Mission-driven work'],
    skills: s('html:3', 'css:3', 'a11y:3', 'javascript:2', 'seo:2', 'responsive:2', 'php:1', 'git:1'),
    seniority: 'mid',
    minYears: 2,
    workMode: 'remote',
    location: 'Remote — Europe',
    region: 'Europe',
    employmentType: 'full-time',
    salaryMin: 48000,
    salaryMax: 62000,
    currency: 'USD',
    tags: ['nonprofit', 'civic'],
    teamSize: 11,
    postedDaysAgo: 12,
    applicants: 28,
  },
  {
    id: 'j13',
    title: 'Lead Frontend Architect',
    company: 'Stratos',
    companyLogo: 'ST',
    blurb: 'Define how 120 engineers build the web at Stratos.',
    description:
      'A leadership role for someone who has already scaled a frontend org. You will own the framework strategy, the module federation architecture, and the difficult conversations about what to deprecate. Deep React and TypeScript expertise assumed.',
    responsibilities: [
      'Own frontend architecture and framework strategy company-wide',
      'Lead the micro-frontend and module federation programme',
      'Set performance budgets and enforce them via CI',
      'Coach staff engineers across four product groups',
    ],
    perks: ['Hybrid', 'Significant equity', 'Executive coaching', 'Sabbatical'],
    skills: s('react:3', 'typescript:3', 'architecture:3', 'webperf:3', 'webpack:2', 'designsystems:2', 'codereview:2', 'collaboration:2'),
    seniority: 'lead',
    minYears: 9,
    workMode: 'hybrid',
    location: 'Singapore',
    region: 'Asia Pacific',
    employmentType: 'full-time',
    salaryMin: 195000,
    salaryMax: 250000,
    currency: 'USD',
    tags: ['saas', 'b2b', 'enterprise'],
    teamSize: 600,
    postedDaysAgo: 10,
    applicants: 39,
  },
  {
    id: 'j14',
    title: 'React Native Engineer',
    company: 'Tidepool',
    companyLogo: 'TP',
    blurb: 'One codebase, two platforms, four million daily users.',
    description:
      'Our mobile app is React Native and it is the primary way people use Tidepool. You will own performance on low-end Android devices, ship native modules when you have to, and keep the release train running weekly.',
    responsibilities: [
      'Build and maintain features in React Native and TypeScript',
      'Profile and fix performance issues on low-end devices',
      'Write native modules in Kotlin and Swift when required',
      'Own the weekly release process',
    ],
    perks: ['Remote APAC', 'Device budget', 'Equity', 'Flexible hours'],
    skills: s('reactnative:3', 'react:3', 'typescript:2', 'testing:2', 'webperf:2', 'kotlin:1', 'cicd:1'),
    seniority: 'mid',
    minYears: 3,
    workMode: 'remote',
    location: 'Remote — APAC',
    region: 'Asia Pacific',
    employmentType: 'full-time',
    salaryMin: 88000,
    salaryMax: 118000,
    currency: 'USD',
    tags: ['consumer', 'mobile', 'social'],
    teamSize: 65,
    postedDaysAgo: 5,
    applicants: 77,
  },
  {
    id: 'j15',
    title: 'Data Visualization Engineer',
    company: 'Northlight Analytics',
    companyLogo: 'NA',
    blurb: 'Make a hundred thousand rows legible at a glance.',
    description:
      'You will build the charting layer of our analytics product — custom D3 and canvas rendering, real-time updates, and interactions that survive a dataset far larger than anyone planned for. Design sense strongly preferred.',
    responsibilities: [
      'Build custom visualizations with D3 and canvas rendering',
      'Keep interactions at 60fps with 100k+ data points',
      'Design chart types collaboratively with the product team',
      'Maintain the shared visualization library',
    ],
    perks: ['Hybrid', 'Conference speaking support', 'Equity', 'Learning budget'],
    skills: s('dataviz:3', 'javascript:3', 'typescript:2', 'react:2', 'css:2', 'webperf:2', 'analytics:1', 'sql:1'),
    seniority: 'senior',
    minYears: 4,
    workMode: 'hybrid',
    location: 'Toronto, Canada',
    region: 'North America',
    employmentType: 'full-time',
    salaryMin: 125000,
    salaryMax: 160000,
    currency: 'USD',
    tags: ['analytics', 'b2b', 'saas'],
    teamSize: 52,
    postedDaysAgo: 6,
    applicants: 54,
  },
  {
    id: 'j16',
    title: 'Frontend Engineering Intern',
    company: 'Lumen Labs',
    companyLogo: 'LL',
    blurb: 'A twelve-week internship with a real, shipped project at the end.',
    description:
      'Our internship is not a shadowing exercise. You get a scoped project, a mentor, and a demo to the whole company at week twelve. Previous interns have shipped the command palette, the theme system and the onboarding tour.',
    responsibilities: [
      'Own a scoped frontend project end to end',
      'Pair with your mentor several times a week',
      'Participate in code review as both author and reviewer',
      'Present your work at the final showcase',
    ],
    perks: ['Paid', 'Housing stipend', 'Return offer track', 'Mentorship'],
    skills: s('javascript:3', 'html:2', 'css:2', 'react:2', 'git:2'),
    seniority: 'intern',
    minYears: 0,
    workMode: 'onsite',
    location: 'San Francisco, CA',
    region: 'North America',
    employmentType: 'internship',
    salaryMin: 45000,
    salaryMax: 60000,
    currency: 'USD',
    tags: ['devtools', 'saas'],
    teamSize: 34,
    postedDaysAgo: 14,
    applicants: 480,
  },
  {
    id: 'j17',
    title: 'Senior Backend Engineer, Python',
    company: 'Terrace',
    companyLogo: 'TC',
    blurb: 'Django at a scale where the ORM starts to fight back.',
    description:
      'Terrace runs a large Django monolith and we are not apologising for it. The interesting work is in query optimisation, background job architecture, and carving out the parts that genuinely need to be separate services.',
    responsibilities: [
      'Own performance of a large Django application',
      'Design the asynchronous task and queue architecture',
      'Optimise Postgres queries and indexing strategy',
      'Extract services from the monolith where it is justified',
    ],
    perks: ['Remote', 'Equity', 'Health cover', 'Annual retreat'],
    skills: s('python:3', 'django:3', 'postgres:3', 'restapi:2', 'redis:2', 'aws:2', 'testing:2', 'docker:1'),
    seniority: 'senior',
    minYears: 5,
    workMode: 'remote',
    location: 'Remote — Latin America',
    region: 'Latin America',
    employmentType: 'full-time',
    salaryMin: 95000,
    salaryMax: 130000,
    currency: 'USD',
    tags: ['marketplace', 'b2c'],
    teamSize: 88,
    postedDaysAgo: 4,
    applicants: 112,
  },
  {
    id: 'j18',
    title: 'Web Developer, Content Platform',
    company: 'Broadsheet Media',
    companyLogo: 'BM',
    blurb: 'Publish to two million readers a day without the site falling over.',
    description:
      'You will work on the publishing platform behind a national news site: the CMS integration, the article rendering pipeline, and the edge caching that keeps it standing during a breaking story. SEO and page speed are not afterthoughts here, they are the business.',
    responsibilities: [
      'Build article and section templates with Next.js',
      'Own edge caching and revalidation strategy',
      'Keep Core Web Vitals green under real editorial load',
      'Integrate with the editorial CMS and its API',
    ],
    perks: ['Hybrid London', 'Pension', 'Press card', 'Cycle scheme'],
    skills: s('nextjs:3', 'react:2', 'seo:3', 'webperf:3', 'edge:2', 'typescript:2', 'css:2', 'restapi:1'),
    seniority: 'mid',
    minYears: 3,
    workMode: 'hybrid',
    location: 'London, UK',
    region: 'Europe',
    employmentType: 'full-time',
    salaryMin: 65000,
    salaryMax: 85000,
    currency: 'USD',
    tags: ['media', 'publishing', 'consumer'],
    teamSize: 40,
    postedDaysAgo: 2,
    applicants: 63,
  },
  {
    id: 'j19',
    title: 'Cloud Infrastructure Engineer',
    company: 'Meridian',
    companyLogo: 'MD',
    blurb: 'Terraform, Kubernetes, and a cloud bill you will personally shrink.',
    description:
      'You will own our AWS footprint end to end — the Terraform modules, the EKS clusters, the cost. We are looking for someone who treats infrastructure as a product with internal customers, not a ticket queue.',
    responsibilities: [
      'Own and evolve Terraform modules across all environments',
      'Operate and upgrade EKS clusters safely',
      'Drive a measurable reduction in cloud spend',
      'Improve incident response and observability tooling',
    ],
    perks: ['Remote US', 'On-call comp', 'Certification budget', 'Equity'],
    skills: s('terraform:3', 'kubernetes:3', 'aws:3', 'docker:2', 'cicd:2', 'observability:2', 'go:1', 'python:1'),
    seniority: 'senior',
    minYears: 5,
    workMode: 'remote',
    location: 'Remote — US',
    region: 'North America',
    employmentType: 'full-time',
    salaryMin: 150000,
    salaryMax: 195000,
    currency: 'USD',
    tags: ['infrastructure', 'b2b'],
    teamSize: 400,
    postedDaysAgo: 11,
    applicants: 49,
  },
  {
    id: 'j20',
    title: 'Product Designer (Front-of-Code)',
    company: 'Aperture',
    companyLogo: 'AP',
    blurb: 'Design in Figma, ship it in the codebase yourself.',
    description:
      'A hybrid role for a designer who commits code. You will own end-to-end product design and then implement the front end of what you designed. Roughly 60% design, 40% engineering.',
    responsibilities: [
      'Own product design from research through to high-fidelity',
      'Implement your own designs in React and Tailwind',
      'Maintain and extend the design system in both Figma and code',
      'Run usability sessions and act on what you learn',
    ],
    perks: ['On-site Berlin', 'Equity', 'Design conference budget', 'Sabbatical'],
    skills: s('uiux:3', 'figma:3', 'designsystems:3', 'css:2', 'react:2', 'tailwind:2', 'html:2', 'a11y:1'),
    seniority: 'senior',
    minYears: 4,
    workMode: 'onsite',
    location: 'Berlin, Germany',
    region: 'Europe',
    employmentType: 'full-time',
    salaryMin: 80000,
    salaryMax: 105000,
    currency: 'USD',
    tags: ['creative', 'media', 'design'],
    teamSize: 45,
    postedDaysAgo: 7,
    applicants: 88,
  },
  {
    id: 'j21',
    title: 'Software Engineer, Realtime Collaboration',
    company: 'Confluence Works',
    companyLogo: 'CW',
    blurb: 'CRDTs, presence, and cursors that never lie.',
    description:
      'We build the collaborative editing layer licensed by a dozen other products. The problems are genuinely hard: conflict-free replicated data types, offline reconciliation, and presence that stays accurate across flaky connections.',
    responsibilities: [
      'Implement and test CRDT-based synchronisation',
      'Build the WebSocket transport and presence layer',
      'Design offline-first reconciliation behaviour',
      'Write the client SDKs used by our licensees',
    ],
    perks: ['Remote', 'Equity', 'Research time', 'Conference speaking'],
    skills: s('typescript:3', 'websockets:3', 'nodejs:2', 'architecture:2', 'testing:2', 'react:2', 'rust:1', 'redis:1'),
    seniority: 'senior',
    minYears: 5,
    workMode: 'remote',
    location: 'Remote — Global',
    region: 'Europe',
    employmentType: 'full-time',
    salaryMin: 140000,
    salaryMax: 180000,
    currency: 'USD',
    tags: ['devtools', 'b2b', 'saas'],
    teamSize: 24,
    postedDaysAgo: 3,
    applicants: 61,
  },
  {
    id: 'j22',
    title: 'Junior Full-Stack Developer',
    company: 'Saffron Commerce',
    companyLogo: 'SC',
    blurb: 'Learn the whole stack on a team that ships every day.',
    description:
      'We run a growing marketplace and we need another pair of hands across the stack. You will touch React on the front and Node on the back, with plenty of review and no expectation that you already know everything.',
    responsibilities: [
      'Build features across a React and Node.js codebase',
      'Write and maintain SQL queries against MySQL',
      'Fix bugs and improve test coverage',
      'Join daily standups and sprint planning',
    ],
    perks: ['Hybrid Bangalore', 'Learning budget', 'Health cover', 'Flexible hours'],
    skills: s('javascript:3', 'react:2', 'nodejs:2', 'sql:2', 'html:2', 'css:2', 'git:2', 'agile:1'),
    seniority: 'junior',
    minYears: 1,
    workMode: 'hybrid',
    location: 'Bangalore, India',
    region: 'Asia Pacific',
    employmentType: 'full-time',
    salaryMin: 18000,
    salaryMax: 28000,
    currency: 'USD',
    tags: ['ecommerce', 'marketplace'],
    teamSize: 55,
    postedDaysAgo: 5,
    applicants: 405,
  },
  {
    id: 'j23',
    title: 'Senior Engineer, Search & Relevance',
    company: 'Northlight Analytics',
    companyLogo: 'NA',
    blurb: 'Ranking, embeddings, and the eternal fight against irrelevant results.',
    description:
      'Search is the product for a lot of our users. You will own the ranking pipeline: lexical retrieval, embedding-based recall, learned reranking, and the evaluation framework that tells us honestly whether a change helped.',
    responsibilities: [
      'Own the retrieval and ranking pipeline end to end',
      'Build offline evaluation harnesses with real relevance judgements',
      'Ship embedding-based recall alongside lexical search',
      'Reduce p99 query latency',
    ],
    perks: ['Hybrid Toronto', 'Equity', 'Research budget', 'Conference travel'],
    skills: s('python:3', 'ml:3', 'llm:2', 'sql:2', 'architecture:2', 'observability:1', 'postgres:1'),
    seniority: 'senior',
    minYears: 5,
    workMode: 'hybrid',
    location: 'Toronto, Canada',
    region: 'North America',
    employmentType: 'full-time',
    salaryMin: 145000,
    salaryMax: 185000,
    currency: 'USD',
    tags: ['ai', 'analytics', 'b2b'],
    teamSize: 52,
    postedDaysAgo: 9,
    applicants: 71,
  },
  {
    id: 'j24',
    title: 'Frontend Engineer, Design Systems',
    company: 'Stratos',
    companyLogo: 'ST',
    blurb: 'Every button in the company goes through you.',
    description:
      'You will own the Stratos design system: 90 components, four product teams, one very high bar for accessibility. The role suits someone who enjoys API design as much as visual detail, and who gets satisfaction from a well-written changelog.',
    responsibilities: [
      'Design, build and version accessible React components',
      'Maintain Storybook documentation and usage guidelines',
      'Run adoption reviews with consuming product teams',
      'Keep the visual language consistent between Figma and code',
    ],
    perks: ['Hybrid Singapore', 'Equity', 'Learning budget', 'Relocation support'],
    skills: s('react:3', 'typescript:3', 'designsystems:3', 'a11y:3', 'css:2', 'testing:2', 'figma:2', 'animation:1'),
    seniority: 'senior',
    minYears: 4,
    workMode: 'hybrid',
    location: 'Singapore',
    region: 'Asia Pacific',
    employmentType: 'full-time',
    salaryMin: 120000,
    salaryMax: 155000,
    currency: 'USD',
    tags: ['saas', 'design systems', 'enterprise'],
    teamSize: 600,
    postedDaysAgo: 6,
    applicants: 82,
  },
  {
    id: 'j25',
    title: 'Web Developer (Part-Time)',
    company: 'Atlas Craft',
    companyLogo: 'AC',
    blurb: 'Twenty hours a week maintaining a beloved indie web app.',
    description:
      'Atlas Craft is a small profitable product with 30,000 paying users. We need someone part-time to keep it healthy: dependency upgrades, bug fixes, small features, and the occasional performance win. Calm work, sensible hours.',
    responsibilities: [
      'Maintain and upgrade an existing Vue and Node codebase',
      'Fix reported bugs and ship small features',
      'Keep dependencies current and the build green',
      'Respond to escalated technical support questions',
    ],
    perks: ['Fully remote', 'Async only', 'Set your own hours', 'No on-call'],
    skills: s('javascript:3', 'vue:2', 'nodejs:2', 'css:2', 'git:2', 'testing:1', 'mysql:1'),
    seniority: 'mid',
    minYears: 2,
    workMode: 'remote',
    location: 'Remote — Global',
    region: 'North America',
    employmentType: 'part-time',
    salaryMin: 40000,
    salaryMax: 55000,
    currency: 'USD',
    tags: ['saas', 'indie', 'b2c'],
    teamSize: 4,
    postedDaysAgo: 15,
    applicants: 22,
  },
  {
    id: 'j26',
    title: 'Engineering Manager, Web',
    company: 'Payload',
    companyLogo: 'PL',
    blurb: 'Lead eight engineers. Stay close enough to the code to be useful.',
    description:
      'A first-line management role for someone who has been a strong senior engineer and wants to grow people. You will run the web platform team: hiring, growth, delivery, and the technical judgement to know when a plan is wishful thinking.',
    responsibilities: [
      'Lead and grow a team of eight web engineers',
      'Own delivery planning and stakeholder communication',
      'Run hiring loops and calibrate the bar',
      'Stay technically credible through review and design input',
    ],
    perks: ['Remote EU', 'Equity', 'Management coaching', 'Offsites'],
    skills: s('collaboration:3', 'codereview:3', 'agile:3', 'architecture:2', 'react:2', 'typescript:2'),
    seniority: 'lead',
    minYears: 7,
    workMode: 'remote',
    location: 'Remote — Europe',
    region: 'Europe',
    employmentType: 'full-time',
    salaryMin: 130000,
    salaryMax: 170000,
    currency: 'USD',
    tags: ['fintech', 'saas', 'leadership'],
    teamSize: 90,
    postedDaysAgo: 13,
    applicants: 35,
  },
]

/** Every domain tag present in the corpus, for the interests picker. */
export const ALL_TAGS = [...new Set(JOBS.flatMap((j) => j.tags))].sort()
